createdAt: '2025-12-06T21:30:34.955041'
platforms: []
settings:
  autoUpdate: true
  maxRetries: 3
  verboseLogging: false
skills:
  agent-creator:
    command: /speckit.dsgs.agent-creator
    description: 智能体创建专家
    enabled: true
  architect:
    command: /speckit.dsgs.architect
    description: 系统架构设计专家
    enabled: true
  constraint-generator:
    command: /speckit.dsgs.constraint-generator
    description: 约束生成专家
    enabled: true
  dapi-checker:
    command: /speckit.dsgs.dapi-checker
    description: 接口检查专家
    enabled: true
  modulizer:
    command: /speckit.dsgs.modulizer
    description: 模块化专家
    enabled: true
  task-decomposer:
    command: /speckit.dsgs.task-decomposer
    description: 任务分解专家
    enabled: true
version: 1.0.0
